/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3.3/userguide/building_java_projects.html
 */

// TODO: Fill in your name here
val YOUR_NAME = "YOUR_NAME_HERE"

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")
    testImplementation("org.assertj:assertj-core:3.22.0")
}

application {
    // Define the main class for the application.
    mainClass.set("csc22100.cellularautomata.Main")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}



tasks.named<Jar>("jar") {
    manifest {
        attributes["Main-Class"] = "csc22100.cellularautomata.Main"
    }
}

tasks.register<Zip>("packageAssignment") {
    archiveFileName.set("${project.name}-$YOUR_NAME.zip")
    from(layout.projectDirectory) {
        include("*.gradle.kts")
        include("src/**")
        include("gradle/**")
        include("gradlew*")
    }

    outputs.upToDateWhen { false }

    finalizedBy(tasks.getByPath("copyZip"))
}

tasks.register<Copy>("copyZip") {
    from(tasks.getByName<Zip>("packageAssignment").outputs)

    destinationDir = layout.projectDirectory.asFile
}

tasks.register<JavaExec>("source2pdf") {
    classpath = files("${project.projectDir}/source2pdf-all.jar")

    args = listOf("src", "-o", "./$YOUR_NAME.pdf")
}